# Generated by Django 4.1.3 on 2022-12-05 14:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название теста')),
                ('description', models.TextField(verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Наборы тестов',
                'db_table': 'group_test',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('type', models.CharField(choices=[('o', 'один правильный ответ'), ('m', 'несколько правильных ответов')], max_length=1, verbose_name='тип вопроса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('group_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grouptest', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_correct', models.PositiveSmallIntegerField(verbose_name='правильные ответы')),
                ('count_not_correct', models.PositiveSmallIntegerField(verbose_name='неправильные ответы')),
                ('result', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='результат')),
                ('best_result', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='лучший результат')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('group_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grouptest', verbose_name='тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='ResponseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=128, verbose_name='ответ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('correct', models.BooleanField(default=False, verbose_name='верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'response',
            },
        ),
    ]
